server.port=8080

spring.data.mongodb.uri=${MONGODB_URI:mongodb+srv://chakrabortychandrasekhar185_db_user:PupjwHgvDA6zc77C@cluster0.y3xiovi.mongodb.net/foodhub?retryWrites=true&w=majority&appName=Cluster0&authSource=admin}

