server.port=8080

# TODO: replace this with your actual MongoDB Atlas URI from .env.local
# Example format:
# spring.data.mongodb.uri=mongodb+srv://user:password@cluster0.xxxxxx.mongodb.net/foodhub?retryWrites=true&w=majority&appName=Cluster0
spring.data.mongodb.uri=mongodb+srv://chakrabortychandrasekhar185_db_user:PupjwHgvDA6zc77C@cluster0.y3xiovi.mongodb.net/foodhub?retryWrites=true&w=majority&appName=Cluster0
